# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 8, 32, 41, 353865, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
